package lti

import (
	"context"
	"time"

	josepkg "github.com/go-jose/go-jose/v3"
	"github.com/go-jose/go-jose/v3/jwt"

	"github.com/marcgabe15/lti-go/internal/idgen"
	internaljose "github.com/marcgabe15/lti-go/internal/jose"
)

// stateClaims is the payload of the signed state JWT this tool issues
// during login and verifies during launch. Because it is signed with the
// platform-specific key pair generated by KeyManager, its mere validity
// proves it was issued by this tool for this specific platform -- no
// server-side session is required to detect tampering or forgery.
type stateClaims struct {
	jwt.Claims
	StateID       string `json:"stateId"`
	TargetLinkURI string `json:"targetLinkUri,omitempty"`
}

func (t *Tool) signState(ctx context.Context, p *Platform, stateID, targetLinkURI string) (string, error) {
	kp, err := t.keyManager.KeyPair(ctx, p.ID)
	if err != nil {
		return "", wrap(ErrInvalidState, err)
	}
	priv, err := internaljose.ParseRSAPrivateKeyPEM(kp.PrivateKey)
	if err != nil {
		return "", wrap(ErrInvalidState, err)
	}
	id, err := idgen.New(16)
	if err != nil {
		return "", wrap(ErrInvalidState, err)
	}
	now := t.now()
	claims := stateClaims{
		Claims: jwt.Claims{
			Issuer:   t.issuer,
			IssuedAt: jwt.NewNumericDate(now),
			Expiry:   jwt.NewNumericDate(now.Add(t.stateTTL)),
			ID:       id,
		},
		StateID:       stateID,
		TargetLinkURI: targetLinkURI,
	}
	token, err := internaljose.SignClaims(priv, kp.KeyID, claims)
	if err != nil {
		return "", wrap(ErrInvalidState, err)
	}
	return token, nil
}

// verifyState verifies that token was issued by this tool for platform,
// and has not expired.
func (t *Tool) verifyState(ctx context.Context, platform *Platform, token string) (*stateClaims, error) {
	kp, err := t.keyManager.KeyPair(ctx, platform.ID)
	if err != nil {
		return nil, wrap(ErrInvalidState, err)
	}
	pub, err := internaljose.ParseRSAPublicKeyPEM(kp.PublicKey)
	if err != nil {
		return nil, wrap(ErrInvalidState, err)
	}
	parsed, err := internaljose.ParseSigned(token)
	if err != nil {
		return nil, wrap(ErrInvalidState, err)
	}
	if err := requireRS256(parsed); err != nil {
		return nil, err
	}

	var claims stateClaims
	if err := internaljose.VerifyWithKey(parsed, pub, &claims); err != nil {
		return nil, wrap(ErrInvalidState, err)
	}
	if claims.Issuer != t.issuer {
		return nil, wrap(ErrInvalidState, errorf(CodeInvalidState, "state issuer %q does not match tool issuer %q", claims.Issuer, t.issuer))
	}
	if err := checkExpiry(claims.Claims, t.now()); err != nil {
		if errCode, _ := CodeOf(err); errCode == CodeTokenExpired {
			return nil, wrap(ErrStateExpired, err)
		}
		return nil, wrap(ErrInvalidState, err)
	}
	return &claims, nil
}

func requireRS256(tok *jwt.JSONWebToken) error {
	for _, h := range tok.Headers {
		if h.Algorithm != string(josepkg.RS256) {
			return errorf(CodeInvalidAlgorithm, "alg %q is not allowed, only RS256 is accepted", h.Algorithm)
		}
	}
	return nil
}

// checkExpiry validates exp/nbf on c against now. It is written out
// explicitly (rather than relying on go-jose's Claims.Validate) so expiry
// semantics stay independently testable and easy to reason about.
func checkExpiry(c jwt.Claims, now time.Time) error {
	if c.Expiry == nil {
		return errorf(CodeInvalidIDToken, "missing exp claim")
	}
	if now.After(c.Expiry.Time()) {
		return wrap(ErrTokenExpired, nil)
	}
	if c.NotBefore != nil && now.Before(c.NotBefore.Time()) {
		return errorf(CodeInvalidIDToken, "token used before nbf")
	}
	return nil
}
